version: '2'
services:
  covid19-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/covid19/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=covid19
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
